// 食谱数据
const recipes = [
  {
    id: 1,
    name: "南瓜小米粥",
    type: "breakfast",
    icon: "🎃",
    description: "适合1岁宝宝，营养丰富",
    ingredients: ["南瓜 50g", "小米 30g", "清水 200ml", "配方奶 50ml (可选)"],
    steps: [
      "南瓜去皮切小块",
      "小米淘洗干净",
      "将南瓜和小米一起放入电饭煲",
      "煮至粘稠即可",
    ],
    notes: [
      "确保南瓜完全煮熟",
      "可根据宝宝喜好调整稠度",
      "首次食用建议少量尝试",
    ],
    image: "/images/pumpkin-porridge.png",
  },
  {
    id: 2,
    name: "胡萝卜土豆泥",
    type: "lunch",
    icon: "🥕",
    description: "富含维生素A，促进视力发育",
    ingredients: ["胡萝卜 60g", "土豆 40g", "配方奶 30ml", "橄榄油 5ml"],
    steps: [
      "胡萝卜和土豆去皮，切成块",
      "蒸锅加水",
      "放入胡萝卜和土豆蒸15分钟",
      "取出后压成泥",
      "加入配方奶和橄榄油",
      "搅拌均匀即可",
    ],
    notes: ["确保食材完全蒸熟", "可根据宝宝喜好调整稠度", "建议现做现吃"],
    image: "/images/carrot-potato.png",
  },
  {
    id: 3,
    name: "菠菜鸡蛋羹",
    type: "dinner",
    icon: "🥬",
    description: "补充铁质，预防贫血",
    ingredients: ["菠菜 30g", "鸡蛋 1个", "盐 少量"],
    steps: [
      "菠菜洗净，焯水，切碎",
      "鸡蛋打散",
      "加入盐",
      "搅拌均匀，倒入容器",
      "蒸锅加水烧开",
      "上锅蒸8-10分钟即可",
    ],
    notes: ["菠菜要焯水去除草酸", "蒸制时间不宜过长", "可根据宝宝喜好调整盐量"],
    image: "/images/spinach-egg.png",
  },
  {
    id: 4,
    name: "苹果燕麦粥",
    type: "breakfast",
    icon: "🍎",
    description: "富含膳食纤维，促进消化",
    ingredients: ["苹果 40g", "燕麦 25g", "配方奶 60ml", "蜂蜜 5ml (可选)"],
    steps: [
      "苹果去皮切丁",
      "燕麦淘洗干净",
      "锅中加水烧开",
      "放入燕麦煮5分钟",
      "加入苹果丁继续煮3分钟",
      "加入配方奶和蜂蜜即可",
    ],
    notes: [
      "苹果要选择甜度适中的",
      "燕麦要选择即食型",
      "蜂蜜1岁以下宝宝不建议食用",
    ],
    image: "/images/apple-oatmeal.png",
  },
  {
    id: 5,
    name: "西兰花鸡肉泥",
    type: "lunch",
    icon: "🥦",
    description: "富含蛋白质和维生素C",
    ingredients: ["西兰花 40g", "鸡胸肉 30g", "橄榄油 5ml"],
    steps: [
      "西兰花洗净切小朵",
      "鸡胸肉切小块",
      "蒸锅加水烧开",
      "放入西兰花和鸡肉蒸12分钟",
      "取出后压成泥",
      "加入橄榄油，搅拌均匀即可",
    ],
    notes: ["确保鸡肉完全煮熟", "西兰花要蒸至软烂", "可根据宝宝喜好调整稠度"],
    image: "/images/broccoli-chicken.png",
  },
  {
    id: 6,
    name: "紫薯山药泥",
    type: "dinner",
    icon: "🍠",
    description: "富含花青素，增强免疫力",
    ingredients: ["紫薯 50g", "山药 30g", "配方奶 40ml", "蜂蜜 5ml (可选)"],
    steps: [
      "紫薯和山药去皮切块",
      "蒸锅加水烧开",
      "放入紫薯和山药蒸20分钟",
      "取出后压成泥",
      "加入配方奶和蜂蜜",
      "搅拌均匀即可",
    ],
    notes: [
      "山药要选择新鲜无斑点的",
      "蒸制时间要足够长",
      "蜂蜜1岁以下宝宝不建议食用",
    ],
    image: "/images/purple-sweet-potato.png",
  },
  {
    id: 7,
    name: "香蕉燕麦粥",
    type: "breakfast",
    icon: "🍌",
    description: "富含钾元素，促进消化",
    ingredients: ["香蕉 50g", "燕麦 30g", "配方奶 60ml"],
    steps: [
      "香蕉去皮切小块",
      "燕麦淘洗干净",
      "锅中加水烧开",
      "放入燕麦煮8分钟",
      "加入香蕉块继续煮2分钟",
      "加入配方奶即可",
    ],
    notes: ["香蕉要选择熟透的", "燕麦要选择即食型", "即煮即食"],
    image: "/images/banana-oatmeal.png",
  },
  {
    id: 8,
    name: "南瓜蒸蛋",
    type: "lunch",
    icon: "🍳",
    description: "营养丰富，口感细腻",
    ingredients: ["南瓜 40g", "鸡蛋 1个", "纯净水 与蛋液的量相等", "盐 一点点"],
    steps: [
      "南瓜去皮切小块",
      "蒸锅加水烧开",
      "放入南瓜蒸至熟透（筷子可以轻易穿透）",
      "蒸好的南瓜放凉，打入一个鸡蛋",
      "加入纯净水和盐，搅拌均匀",
      "上锅蒸8-10分钟即可",
    ],
    notes: ["确保南瓜完全煮熟", "蒸制时间不宜过长", "可根据宝宝喜好调整盐量"],
    image: "/images/pumpkin-egg.png",
  },
  {
    id: 9,
    name: "青菜豆腐汤",
    type: "dinner",
    icon: "🥬",
    description: "清淡易消化，补充蛋白质",
    ingredients: ["青菜 30g", "嫩豆腐 50g", "纯净水 200ml", "盐 少许"],
    steps: [
      "青菜洗净切碎",
      "豆腐切小块",
      "锅中加入纯净水烧开",
      "放入豆腐煮3分钟",
      "加入青菜继续煮2分钟",
      "加盐调味即可",
    ],
    notes: ["青菜要选择嫩叶", "豆腐要选择嫩豆腐"],
    image: "/images/vegetable-tofu.png",
  },
  {
    id: 10,
    name: "香蕉松饼",
    type: "breakfast",
    icon: "🍌",
    description: "富含钾元素，促进消化",
    ingredients: ["一根香蕉", "鸡蛋蛋黄 2 个", "低筋面粉 适量"],
    steps: [
      "香蕉剥皮",
      "鸡蛋蛋黄打散",
      "香蕉和蛋黄混合，放入辅食机打至细腻",
      "面粉少量多次加入，调至黏稠酸奶状为止",
      "不粘锅倒入面糊，全程开小火",
      "煎至两面金黄即可",
    ],
    notes: [
      "香蕉选择熟透的，成品会更香甜",
      "鸡蛋要选择新鲜的",
      "可以使用空气炸锅，面糊倒入硅油纸盘，145 度/10 分钟，更方便",
      "吃不完的可以放冰箱冷冻，吃的时候再加热",
    ],
    image: "/images/carrot-egg.png",
  },
  {
    id: 11,
    name: "胡萝卜牛肉肠",
    type: "dinner",
    icon: "🥕",
    description: "富含维生素A，促进视力发育",
    ingredients: [
      "胡萝卜 80g",
      "牛肉 80g",
      "鸡蛋蛋清 1个",
      "面粉 20g",
      "玉米淀粉 2g",
    ],
    steps: [
      "胡萝卜去皮切小块",
      "牛肉切小块",
      "所有食材一起放入辅食机，打成泥",
      "装入裱花袋，在锡纸上挤成条状",
      "每挤完一条，用锡纸卷成香肠状",
      "冷水上锅蒸20分钟，焖5分钟",
      "剥开锡纸即可",
    ],
    notes: [
      "要选择新鲜的食材",
      "用辅食机打完以后，食材混合物状态比酸奶更稠。如果太稀就继续加面粉",
      "冷水上锅蒸20分钟，焖5分钟",
      "剥开锡纸即可",
    ],
    image: "/images/tomato-egg.png",
  },
  {
    id: 12,
    name: "苹果松饼",
    type: "lunch",
    icon: "🍎",
    description: "富含膳食纤维，促进消化",
    ingredients: ["苹果 30g", "鸡蛋 1个", "面粉 适量"],
    steps: [
      "苹果去皮切小块",
      "鸡蛋打散",
      "苹果和鸡蛋混合，放入辅食机打至细腻",
      "面粉少量多次加入，调至黏稠酸奶状为止",
      "不粘锅倒入面糊，全程开小火",
      "煎至两面金黄即可",
    ],
    notes: [
      "苹果要选择甜度适中的",
      "鸡蛋要选择新鲜的",
      "可以使用空气炸锅，面糊倒入硅油纸盘，145 度/10 分钟，更方便",
      "吃不完的可以放冰箱冷冻，吃的时候再加热",
    ],
    image: "/images/apple-oatmeal.png",
  }
];

// 常见过敏食材
const commonAllergies = [
  { name: "花生", icon: "🥜" },
  { name: "鸡蛋", icon: "🥚" },
  { name: "牛奶", icon: "🥛" },
  { name: "虾", icon: "🦐" },
  { name: "蟹", icon: "🦀" },
  { name: "坚果", icon: "🥜" },
  { name: "小麦", icon: "🌾" },
  { name: "大豆", icon: "🫘" },
  { name: "鱼类", icon: "🐟" },
  { name: "苹果", icon: "🍎" },
  { name: "桃子", icon: "🍑" },
  { name: "草莓", icon: "🍓" },
];

module.exports = {
  recipes,
  commonAllergies,
};
