// 食谱数据
const recipes = [
  {
    id: 1,
    name: "南瓜小米粥",
    type: "breakfast",
    icon: "🎃",
    description: "适合1岁宝宝，营养丰富",
    ingredients: [
      "南瓜 50g",
      "小米 30g",
      "清水 200ml",
      "配方奶 50ml（可选⚠️易过敏）",
    ],
    steps: [
      "南瓜去皮切小块",
      "小米淘洗干净",
      "将南瓜和小米一起放入电饭煲",
      "煮至粘稠即可",
    ],
    notes: [
      "确保南瓜完全煮熟",
      "可根据宝宝喜好调整稠度",
      "首次食用建议少量尝试",
    ],
    image: "/images/pumpkin-porridge.png",
  },
  {
    id: 2,
    name: "苹果泥",
    type: "snack",
    icon: "🍎",
    description: "口感细腻，富含维生素C",
    ingredients: ["苹果 1个（约150g）"],
    steps: ["苹果去皮去核", "擦成泥或用搅拌机打泥", "可用温水调节浓度"],
    notes: ["选用红富士等甜苹果", "避免使用酸涩口味", "适合6个月以上宝宝"],
    image: "/images/apple-puree.png",
  },
  {
    id: 3,
    name: "胡萝卜米糊",
    type: "breakfast",
    icon: "🥕",
    description: "富含维A，有助宝宝视觉发育",
    ingredients: ["胡萝卜 40g", "婴儿米粉 20g", "温水 150ml"],
    steps: ["胡萝卜蒸熟后打成泥", "用温水调米粉", "混合胡萝卜泥搅拌均匀"],
    notes: [
      "胡萝卜需彻底蒸软",
      "可搭配配方奶增加口感（⚠️易过敏）",
      "适合7个月以上宝宝",
    ],
    image: "/images/carrot-cereal.png",
  },
  {
    id: 4,
    name: "香蕉泥",
    type: "snack",
    icon: "🍌",
    description: "软糯香甜，缓解便秘",
    ingredients: ["香蕉 1根（约80g）"],
    steps: ["香蕉去皮", "用勺子压成泥状", "直接喂食或加少许温水"],
    notes: ["香蕉应熟透且无黑斑", "避免冷藏直接食用", "适合6个月以上宝宝"],
    image: "/images/banana-mash.png",
  },
  {
    id: 5,
    name: "山药米糊",
    type: "breakfast",
    icon: "🍠",
    description: "助消化，增强抵抗力",
    ingredients: ["山药 30g", "米粉 20g"],
    steps: ["山药去皮切片蒸熟", "压成泥后混入米粉", "加入适量温水搅匀"],
    notes: [
      "山药易过敏，初次喂食请观察",
      "去皮时建议戴手套",
      "适合7个月以上宝宝",
    ],
    image: "/images/yam-cereal.png",
  },
  {
    id: 6,
    name: "鸡蛋羹",
    type: "dinner",
    icon: "🥚",
    description: "高蛋白易消化，适合晚餐",
    ingredients: ["鸡蛋 1个（⚠️易过敏）", "温水 100ml"],
    steps: [
      "打散鸡蛋与温水按1:2比例搅匀",
      "过滤泡沫，入碗蒸10分钟",
      "表面光滑即可食用",
    ],
    notes: ["首次尝试建议只用蛋黄", "避免蒸过熟口感老硬", "适合8个月以上宝宝"],
    image: "/images/egg-custard.png",
  },
  {
    id: 7,
    name: "红薯泥",
    type: "snack",
    icon: "🍠",
    description: "富含膳食纤维，口感甜糯",
    ingredients: ["红薯 50g"],
    steps: ["红薯蒸熟或烤熟", "去皮后压成泥", "可加少许温水调稀"],
    notes: [
      "不建议空腹食用红薯",
      "如有便秘可增加喂食次数",
      "适合6个月以上宝宝",
    ],
    image: "/images/sweetpotato-puree.png",
  },
  {
    id: 8,
    name: "豌豆胡萝卜泥",
    type: "lunch",
    icon: "🟢",
    description: "多种蔬菜组合，丰富纤维",
    ingredients: ["豌豆仁 30g", "胡萝卜 30g"],
    steps: ["豌豆煮熟去皮打泥", "胡萝卜蒸熟压泥", "混合搅匀"],
    notes: ["豌豆需去皮防止胀气", "颜色鲜艳宝宝更爱吃", "适合8个月以上宝宝"],
    image: "/images/pea-carrot.png",
  },
  {
    id: 9,
    name: "牛油果香蕉泥",
    type: "snack",
    icon: "🥑",
    description: "高脂肪、高能量，促进脑发育",
    ingredients: ["牛油果 30g（⚠️易过敏）", "香蕉 30g"],
    steps: ["牛油果去皮去核取果肉", "香蕉去皮压泥", "混合搅拌均匀即可"],
    notes: [
      "牛油果熟透后才易消化",
      "建议立即食用避免氧化",
      "适合9个月以上宝宝",
    ],
    image: "/images/avocado-banana.png",
  },
  {
    id: 10,
    name: "南瓜藜麦粥",
    type: "breakfast",
    icon: "🌾",
    description: "膳食纤维丰富，助消化",
    ingredients: ["南瓜 40g", "藜麦 20g", "清水 200ml"],
    steps: ["藜麦提前浸泡1小时", "南瓜蒸熟压泥", "两者一起熬煮成粥"],
    notes: [
      "藜麦含植物蛋白，营养全面",
      "粥煮至软糯无颗粒为宜",
      "适合9个月以上宝宝",
    ],
    image: "/images/quinoa-pumpkin.png",
  },
  {
    id: 11,
    name: "红薯糊糊",
    type: "breakfast",
    icon: "🍠",
    description: "口感软糯，易于吞咽",
    ingredients: ["红薯 60g"],
    steps: ["红薯去皮切片蒸熟", "压成泥或打成糊", "根据稠度加水调节"],
    notes: ["红薯甜度高，控制摄入量", "适合便秘宝宝", "冷却后更绵软"],
    image: "/images/sweetpotato-puree.png",
  },
  {
    id: 12,
    name: "西兰花土豆泥",
    type: "lunch",
    icon: "🥦",
    description: "含铁丰富，绿色营养",
    ingredients: ["西兰花 30g", "土豆 50g"],
    steps: [
      "西兰花焯水、土豆蒸熟",
      "一同打泥或压碎搅匀",
      "调整稠度适合宝宝口感",
    ],
    notes: [
      "西兰花不要久煮",
      "初次尝试绿色蔬菜建议搭配口味温和食材",
      "适合10个月以上宝宝",
    ],
    image: "/images/broccoli-potato.png",
  },
  {
    id: 13,
    name: "牛肉番茄粥",
    type: "lunch",
    icon: "🥩",
    description: "补铁补锌，助力发育",
    ingredients: ["牛肉末 30g", "番茄 30g", "大米 30g"],
    steps: ["番茄去皮切碎，牛肉焯水去腥", "与大米一同熬粥", "煮至米烂成粥状"],
    notes: ["牛肉可选低脂瘦肉", "番茄去籽防止刺激", "适合9个月以上宝宝"],
    image: "/images/beef-tomato.png",
  },
  {
    id: 14,
    name: "玉米胡萝卜粥",
    type: "dinner",
    icon: "🌽",
    description: "口感香甜，宝宝喜爱",
    ingredients: ["玉米粒 20g", "胡萝卜 30g", "大米 30g"],
    steps: ["胡萝卜切丁、玉米煮熟打泥", "与大米一起煮成粥", "搅拌均匀即可"],
    notes: ["玉米须细打泥避免颗粒", "颜色鲜艳引发食欲", "适合8个月以上宝宝"],
    image: "/images/corn-carrot.png",
  },
  {
    id: 15,
    name: "藜麦鸡肉泥",
    type: "lunch",
    icon: "🍚",
    description: "高蛋白低敏粮食",
    ingredients: ["藜麦 30g", "鸡肉 30g"],
    steps: ["藜麦提前浸泡去苦味", "鸡肉煮熟打碎", "混合煮熟搅拌成泥"],
    notes: [
      "注意藜麦是否彻底煮熟",
      "可添加南瓜泥调整口感",
      "适合10个月以上宝宝",
    ],
    image: "/images/quinoa-chicken.png",
  },
  {
    id: 16,
    name: "山药猪肝粥",
    type: "lunch",
    icon: "🧄",
    description: "高铁食谱，改善贫血",
    ingredients: ["猪肝 20g（⚠️易过敏）", "山药 40g", "大米 30g"],
    steps: ["猪肝焯水去腥，切细末", "山药去皮切块蒸熟", "所有材料煮粥搅匀"],
    notes: [
      "猪肝初次添加需谨慎",
      "控制摄入频率（1周1-2次）",
      "适合11个月以上宝宝",
    ],
    image: "/images/liver-rice.png",
  },
  {
    id: 17,
    name: "冬瓜虾仁粥",
    type: "dinner",
    icon: "🦐",
    description: "低脂清淡，口感鲜美",
    ingredients: ["冬瓜 40g", "虾仁 20g（⚠️易过敏）", "小米 30g"],
    steps: ["冬瓜切丁、虾仁去壳去肠线剁碎", "与小米一起熬粥", "熟后搅拌均匀"],
    notes: ["虾仁首次添加注意过敏反应", "冬瓜不宜生食", "适合10个月以上宝宝"],
    image: "/images/wintermelon-shrimp.png",
  },
  {
    id: 18,
    name: "紫薯奶酪糊",
    type: "breakfast",
    icon: "🧀",
    description: "钙质丰富，增强骨骼",
    ingredients: ["紫薯 40g", "宝宝奶酪 15g（⚠️易过敏）"],
    steps: ["紫薯蒸熟压泥", "混合奶酪搅匀加热", "搅拌至糊状即可"],
    notes: [
      "宝宝专用奶酪含盐量低",
      "奶制品需观察过敏反应",
      "适合10个月以上宝宝",
    ],
    image: "/images/cheese-yam.png",
  },
  {
    id: 19,
    name: "藕粉米糊",
    type: "breakfast",
    icon: "🥣",
    description: "健脾开胃、易于吸收",
    ingredients: ["藕粉 10g", "婴儿米粉 20g", "温水 150ml"],
    steps: ["藕粉与米粉先干混合", "缓缓加入温水搅匀", "冲调至无颗粒状态"],
    notes: [
      "注意藕粉冲调水温不可过热",
      "调稀一点更易吞咽",
      "适合6个月以上宝宝",
    ],
    image: "/images/lotus-powder.png",
  },
  {
    id: 20,
    name: "牛油果香蕉糊",
    type: "snack",
    icon: "🥑",
    description: "好脂肪与碳水化合物结合",
    ingredients: ["熟牛油果 30g", "熟香蕉 30g"],
    steps: ["两者压泥或搅拌打糊", "无需加热直接喂食"],
    notes: ["香蕉和牛油果均应熟透", "避免吃太凉", "适合7个月以上宝宝"],
    image: "/images/avocado-banana.png",
  },
  {
    id: 21,
    name: "南瓜玉米糊",
    type: "breakfast",
    icon: "🌽",
    description: "色香味俱全，适合挑食宝宝",
    ingredients: ["南瓜 40g", "甜玉米粒 30g"],
    steps: ["玉米蒸熟打成泥", "南瓜蒸熟压成泥", "混合搅匀即可"],
    notes: [
      "玉米需充分打碎避免颗粒",
      "南瓜选择板栗南瓜更香甜",
      "适合8个月以上宝宝",
    ],
    image: "/images/pumpkin-corn.png",
  },
  {
    id: 22,
    name: "苹果胡萝卜泥",
    type: "snack",
    icon: "🍏",
    description: "维生素丰富，帮助视觉发育",
    ingredients: ["苹果 50g", "胡萝卜 30g"],
    steps: ["胡萝卜蒸熟压泥", "苹果去皮生磨成泥", "混合后搅匀即可"],
    notes: ["苹果不需加热", "胡萝卜需熟透口感更佳", "适合6个月以上宝宝"],
    image: "/images/apple-carrot.png",
  },
  {
    id: 23,
    name: "山药青菜粥",
    type: "dinner",
    icon: "🌿",
    description: "温和助消化，适合换季时节",
    ingredients: ["山药 30g", "青菜叶 20g", "大米 30g"],
    steps: ["山药蒸熟压泥", "青菜焯水切细末", "与大米一起熬粥"],
    notes: ["注意去皮防过敏", "菜叶切碎避免噎食", "适合9个月以上宝宝"],
    image: "/images/yam-greenrice.png",
  },
  {
    id: 24,
    name: "南瓜鸡蛋羹",
    type: "dinner",
    icon: "🍮",
    description: "丰富蛋白质与胡萝卜素",
    ingredients: ["南瓜 40g", "鸡蛋 1个（⚠️易过敏）"],
    steps: ["南瓜蒸熟打泥", "鸡蛋打散混合南瓜泥", "蒸10分钟即可"],
    notes: [
      "初次喂蛋建议分次添加",
      "确保熟透避免生蛋风险",
      "适合10个月以上宝宝",
    ],
    image: "/images/pumpkin-egg.png",
  },
  {
    id: 25,
    name: "豆腐胡萝卜泥",
    type: "lunch",
    icon: "🥣",
    description: "蛋白质丰富，口感细腻",
    ingredients: ["嫩豆腐 50g（⚠️易过敏）", "胡萝卜 30g"],
    steps: ["豆腐焯水后压碎", "胡萝卜蒸熟打泥", "混合搅匀加热即可"],
    notes: [
      "豆腐口感滑嫩，适合初期辅食",
      "胡萝卜蒸熟口感更佳",
      "适合7个月以上宝宝",
    ],
    image: "/images/tofu-carrot.png",
  },
  {
    id: 26,
    name: "豌豆米糊",
    type: "lunch",
    icon: "🫛",
    description: "绿色高纤，调节肠道功能",
    ingredients: ["去皮豌豆 30g", "婴儿米粉 20g"],
    steps: ["豌豆蒸熟压泥或搅碎过滤", "加入已调好的米粉糊中", "搅拌均匀喂食"],
    notes: [
      "豌豆务必去皮避免难消化",
      "绿色蔬菜适量添加即可",
      "适合8个月以上宝宝",
    ],
    image: "/images/pea-cereal.png",
  },
  {
    id: 27,
    name: "香蕉藜麦糊",
    type: "breakfast",
    icon: "🍌",
    description: "增强饱腹感，能量满满",
    ingredients: ["香蕉 40g", "藜麦熟糊 30g"],
    steps: ["藜麦煮熟打成泥糊状", "香蕉压泥混合其中", "拌匀即可食用"],
    notes: ["藜麦预先浸泡后更好煮", "香蕉务必熟透无涩味", "适合10个月以上宝宝"],
    image: "/images/banana-quinoa.png",
  },
  {
    id: 28,
    name: "苹果山药糊",
    type: "snack",
    icon: "🍎",
    description: "健脾助消化，味道清甜",
    ingredients: ["苹果 40g", "山药 30g"],
    steps: ["山药蒸熟压泥", "苹果擦泥后混合其中", "拌匀即可喂食"],
    notes: [
      "山药需彻底熟透避免痒口",
      "苹果不建议加热保持营养",
      "适合7个月以上宝宝",
    ],
    image: "/images/apple-yam.png",
  },
  {
    id: 29,
    name: "西葫芦鸡肉泥",
    type: "lunch",
    icon: "🥒",
    description: "低脂高蛋白，清淡不腻",
    ingredients: ["西葫芦 40g", "鸡胸肉 30g"],
    steps: ["鸡胸肉煮熟剁碎", "西葫芦蒸熟压泥", "两者混合加热搅拌"],
    notes: [
      "西葫芦口感滑嫩，易消化",
      "鸡肉打碎避免咀嚼困难",
      "适合9个月以上宝宝",
    ],
    image: "/images/zucchini-chicken.png",
  },
  {
    id: 30,
    name: "紫甘蓝土豆泥",
    type: "dinner",
    icon: "🥬",
    description: "抗氧化强，色彩鲜艳",
    ingredients: ["紫甘蓝叶 20g", "土豆 50g"],
    steps: ["紫甘蓝焯水切碎", "土豆蒸熟压泥", "两者混合搅拌均匀"],
    notes: ["颜色艳丽可激发食欲", "紫甘蓝初加建议少量", "适合10个月以上宝宝"],
    image: "/images/cabbage-potato.png",
  },
  {
    id: 31,
    name: "黑芝麻糊",
    type: "breakfast",
    icon: "🌰",
    description: "补钙护发，香浓细滑",
    ingredients: ["熟黑芝麻粉 5g（⚠️易过敏）", "婴儿米粉 20g", "温水 150ml"],
    steps: ["黑芝麻粉和米粉干混合", "缓缓加入温水搅匀", "冲至顺滑无颗粒"],
    notes: [
      "初次添加黑芝麻应少量尝试",
      "冲调温度约40~50℃为宜",
      "适合10个月以上宝宝",
    ],
    image: "/images/black-sesame.png",
  },
  {
    id: 32,
    name: "红枣山药泥",
    type: "snack",
    icon: "🍠",
    description: "补血养脾，甜润可口",
    ingredients: ["红枣去核 3颗", "山药 50g"],
    steps: [
      "红枣泡软蒸熟，山药去皮蒸熟",
      "一起压成泥搅匀",
      "根据稠度适量加温水",
    ],
    notes: [
      "避免红枣皮造成噎食",
      "山药可提前用醋水泡防氧化",
      "适合10个月以上宝宝",
    ],
    image: "/images/date-yam.png",
  },
  {
    id: 33,
    name: "青豆米粥",
    type: "lunch",
    icon: "🟢",
    description: "绿色营养，利于消化",
    ingredients: ["青豆仁 30g", "大米 30g"],
    steps: ["青豆煮熟打泥或过筛", "与大米一起煮粥", "粥熟后搅匀"],
    notes: ["注意去豆皮防胀气", "米粥可先用电饭煲预约", "适合9个月以上宝宝"],
    image: "/images/pea-rice.png",
  },
  {
    id: 34,
    name: "茄子牛肉泥",
    type: "lunch",
    icon: "🍆",
    description: "增强免疫力，口味独特",
    ingredients: ["茄子 40g", "牛肉末 30g"],
    steps: ["茄子去皮蒸软，牛肉煮熟剁碎", "两者混合压泥搅拌", "适量加水调稠度"],
    notes: ["茄子初次添加观察反应", "牛肉选瘦无筋部分", "适合11个月以上宝宝"],
    image: "/images/eggplant-beef.png",
  },
  {
    id: 35,
    name: "奶香西米露",
    type: "snack",
    icon: "🥛",
    description: "香甜软糯，满足口感需求",
    ingredients: ["宝宝配方奶 80ml（⚠️易过敏）", "西米 15g"],
    steps: [
      "西米煮透后泡凉水去粘性",
      "重新加热后加入配方奶搅匀",
      "搅拌至均匀即可",
    ],
    notes: ["注意西米煮透防止噎食", "不建议加入糖类", "适合11个月以上宝宝"],
    image: "/images/milk-sago.png",
  },
  {
    id: 36,
    name: "紫薯鸡蛋羹",
    type: "dinner",
    icon: "🍠",
    description: "营养均衡，色泽诱人",
    ingredients: ["紫薯 40g", "鸡蛋 1个（⚠️易过敏）"],
    steps: ["紫薯蒸熟压泥", "鸡蛋打匀，与紫薯混合", "蒸熟至凝固即可"],
    notes: ["蛋液打匀更嫩滑", "紫薯增加甜味和色彩", "适合10个月以上宝宝"],
    image: "/images/yam-egg.png",
  },
  {
    id: 37,
    name: "南瓜藜麦粥",
    type: "breakfast",
    icon: "🥣",
    description: "膳食纤维丰富，适合清晨",
    ingredients: ["南瓜 40g", "藜麦 30g"],
    steps: ["南瓜蒸熟压泥，藜麦煮熟", "混合煮粥搅拌均匀", "搅拌至适口即可"],
    notes: ["藜麦需提前浸泡1小时", "适合调理肠胃", "适合10个月以上宝宝"],
    image: "/images/pumpkin-quinoa.png",
  },
  {
    id: 38,
    name: "西葫芦奶糊",
    type: "dinner",
    icon: "🥒",
    description: "清爽润滑，利尿助消化",
    ingredients: ["西葫芦 40g", "配方奶 50ml（⚠️易过敏）"],
    steps: ["西葫芦去皮蒸熟压泥", "配方奶加热至40℃左右", "搅匀后喂食"],
    notes: ["避免奶太烫", "西葫芦水分足不需额外加水", "适合9个月以上宝宝"],
    image: "/images/zucchini-milk.png",
  },
  {
    id: 39,
    name: "苹果糙米粥",
    type: "breakfast",
    icon: "🍎",
    description: "天然甜味，助消化",
    ingredients: ["苹果 50g", "糙米 30g"],
    steps: ["苹果切丁，糙米泡软", "一同煮至粥状搅匀", "必要时可打糊"],
    notes: [
      "糙米口感粗糙需充分煮",
      "苹果建议选红富士甜口品种",
      "适合9个月以上宝宝",
    ],
    image: "/images/apple-brownrice.png",
  },
  {
    id: 40,
    name: "南瓜红枣小米粥",
    type: "breakfast",
    icon: "🎃",
    description: "香甜软糯，润肺健脾",
    ingredients: ["南瓜 40g", "红枣 2颗", "小米 30g"],
    steps: ["红枣去核蒸熟切碎", "南瓜蒸熟压泥", "与小米煮粥搅匀即可"],
    notes: [
      "红枣不要整颗喂食",
      "初次尝试注意观察大便情况",
      "适合10个月以上宝宝",
    ],
    image: "/images/pumpkin-date.png",
  },
  {
    id: 41,
    name: "银耳雪梨糊",
    type: "snack",
    icon: "🍐",
    description: "润肺止咳，适合干燥季节",
    ingredients: ["银耳 5g", "雪梨 50g"],
    steps: ["银耳泡发后剪碎炖软", "雪梨切丁蒸熟打糊", "两者混合搅拌加热"],
    notes: ["银耳需充分炖软防止噎食", "建议秋冬季节食用", "适合11个月以上宝宝"],
    image: "/images/pear-soup.png",
  },
  {
    id: 42,
    name: "绿豆莲子粥",
    type: "lunch",
    icon: "🥣",
    description: "清热去火，夏季推荐",
    ingredients: ["绿豆 20g", "莲子 10g", "大米 30g"],
    steps: ["绿豆和莲子提前浸泡", "与大米一起熬粥煮软", "必要时压碎成泥"],
    notes: ["莲子去芯防苦", "适合夏季清淡饮食", "适合10个月以上宝宝"],
    image: "/images/munglotus-rice.png",
  },
  {
    id: 43,
    name: "胡萝卜猪肉泥",
    type: "lunch",
    icon: "🥕",
    description: "补铁健脾，口味香甜",
    ingredients: ["猪瘦肉末 30g", "胡萝卜 40g"],
    steps: ["猪肉煮熟剁碎", "胡萝卜蒸熟打泥", "混合加热搅拌均匀"],
    notes: ["胡萝卜甜味能遮盖肉腥味", "肉末打碎易吞咽", "适合9个月以上宝宝"],
    image: "/images/pork-carrot.png",
  },
  {
    id: 44,
    name: "菠菜豆腐泥",
    type: "lunch",
    icon: "🥬",
    description: "含铁补钙，绿色营养",
    ingredients: ["菠菜叶 30g", "嫩豆腐 50g（⚠️易过敏）"],
    steps: ["菠菜焯水去草酸后切碎", "豆腐焯水后压碎", "混合搅拌加热"],
    notes: [
      "菠菜用菜心嫩叶部分",
      "注意观察豆制品过敏反应",
      "适合9个月以上宝宝",
    ],
    image: "/images/spinach-tofu.png",
  },
  {
    id: 45,
    name: "山药鸡蛋软饼",
    type: "snack",
    icon: "🥚",
    description: "锻炼抓握力，营养饱腹",
    ingredients: ["山药泥 40g", "鸡蛋 1个（⚠️易过敏）", "低筋面粉 20g"],
    steps: ["材料搅匀成糊状", "平底锅煎熟成小饼", "晾凉后手拿食用"],
    notes: ["适合练习自主进食", "初次加蛋建议只用蛋黄", "适合10个月以上宝宝"],
    image: "/images/yam-eggcake.png",
  },
  {
    id: 46,
    name: "紫甘蓝苹果泥",
    type: "snack",
    icon: "💜",
    description: "护眼抗氧化，酸甜可口",
    ingredients: ["紫甘蓝叶 20g", "苹果 40g"],
    steps: ["紫甘蓝焯水切碎打泥", "苹果擦泥混合其中", "拌匀即可"],
    notes: [
      "紫甘蓝颜色易染色注意衣物",
      "苹果不加热保留维C",
      "适合8个月以上宝宝",
    ],
    image: "/images/redcabbage-apple.png",
  },
  {
    id: 47,
    name: "香蕉南瓜小米粥",
    type: "breakfast",
    icon: "🍌",
    description: "润肠通便，改善便秘",
    ingredients: ["香蕉 30g", "南瓜 30g", "小米 30g"],
    steps: ["南瓜蒸熟压泥，小米煮粥", "粥好后加入香蕉压泥搅匀", "可打糊喂食"],
    notes: ["香蕉要熟透", "避免糖分过高，适量即可", "适合8个月以上宝宝"],
    image: "/images/banana-pumpkin-millet.png",
  },
  {
    id: 48,
    name: "青菜鸡蛋米糊",
    type: "breakfast",
    icon: "🍳",
    description: "清新口感，增强免疫",
    ingredients: ["青菜叶 20g", "鸡蛋黄 1个（⚠️易过敏）", "米粉 20g"],
    steps: ["青菜焯水切碎", "鸡蛋煮熟取蛋黄压碎", "与米粉混合搅匀冲调"],
    notes: ["适合初期尝试蛋类宝宝", "青菜细碎可防止噎食", "适合7个月以上宝宝"],
    image: "/images/egg-greenrice.png",
  },
  {
    id: 49,
    name: "番茄龙利鱼粥",
    type: "lunch",
    icon: "🐟",
    description: "富含DHA，促进大脑发育",
    ingredients: ["龙利鱼肉 30g（⚠️易过敏）", "番茄 30g", "大米 30g"],
    steps: ["番茄去皮切碎，鱼肉蒸熟剁碎", "与米一起煮成粥", "搅拌均匀喂食"],
    notes: ["鱼类初尝应少量添加", "番茄建议去籽", "适合10个月以上宝宝"],
    image: "/images/fish-tomato.png",
  },
  {
    id: 50,
    name: "黑豆红枣粥",
    type: "dinner",
    icon: "🫘",
    description: "补血补铁，增强体质",
    ingredients: ["黑豆 20g", "红枣 2颗", "大米 30g"],
    steps: ["黑豆和红枣提前泡软", "去枣核，与大米煮粥", "熟后打泥或搅拌均匀"],
    notes: ["黑豆初尝建议打碎后食用", "红枣需去核防噎", "适合10个月以上宝宝"],
    image: "/images/blackbean-date.png",
  },
];

// 常见过敏食材
const commonAllergies = [
  { name: "花生", icon: "🥜" },
  { name: "鸡蛋", icon: "🥚" },
  { name: "牛奶", icon: "🥛" },
  { name: "虾", icon: "🦐" },
  { name: "蟹", icon: "🦀" },
  { name: "坚果", icon: "🥜" },
  { name: "小麦", icon: "🌾" },
  { name: "大豆", icon: "🫘" },
  { name: "鱼类", icon: "🐟" },
  { name: "苹果", icon: "🍎" },
  { name: "桃子", icon: "🍑" },
  { name: "草莓", icon: "🍓" },
];

module.exports = {
  recipes,
  commonAllergies,
};
